# WeYa PMC Leader

- type: entity
  parent: MarkerBase
  id: RMCSpawnerPMCLeader
  name: We-Ya PMC Leader spawner
  suffix: Spawner
  components:
    - type: Sprite
      layers:
      - state: red
      - sprite: _RMC14/Objects/Clothing/Uniforms/PMC/officer.rsi
        state: icon
    - type: ConditionalSpawner
      prototypes:
      - RMCRandomHumanoidPMCLeader

- type: entity
  id: RMCRandomHumanoidPMCLeader
  name: We-Ya PMC Leader ghost role
  suffix: Role
  components:
    - type: Sprite
      sprite: _RMC14/Objects/Clothing/Uniforms/PMC/officer.rsi
      state: icon
    - type: RandomHumanoidSpawner
      settings: RMCPMCLeader

- type: randomHumanoidSettings
  parent: EventHumanoid
  id: RMCPMCLeader
  components:
    - type: GhostRole
      name: rmc-ghost-role-information-pmc-leader-name
      description: rmc-ghost-role-information-pmc-standard-description
      rules: ghost-role-information-nonantagonist-rules
      raffle:
        settings: short
    - type: Loadout
      prototypes: [ RMCGearPMCLeader ]

- type: startingGear
  id: RMCGearPMCLeader
  equipment:
    # head: /obj/item/clothing/head/helmet/marine/veteran/pmc/leader
    back: CMBackpack # /obj/item/storage/backpack/lightpack
    gloves: RMCHandsVeteranPMC
    jumpsuit: RMCJumpsuitVeteranPMCLeader
    # outerClothing: /obj/item/clothing/suit/storage/marine/veteran/pmc/leader
    shoes: CMBootsBlackFilled
    id: RMCIDCardPMC
    ears: RMCHeadsetDistressPMC
    # pocket1: /obj/item/storage/pouch/magazine/large/pmc_rifle
    pocket2: CMPouchFirstAidInjectors
