# We-Ya PMC

- type: entity
  parent: MarkerBase
  id: RMCSpawnerPMCStandard
  name: We-Ya PMC Standard spawner
  suffix: Spawner
  components:
    - type: Sprite
      layers:
      - state: red
      - sprite: _RMC14/Objects/Clothing/Uniforms/PMC/standard.rsi
        state: icon
    - type: ConditionalSpawner
      prototypes:
      - RMCRandomHumanoidPMCStandard

- type: entity
  id: RMCRandomHumanoidPMCStandard
  name: We-Ya PMC Standard ghost role
  suffix: Role
  components:
    - type: Sprite
      sprite: _RMC14/Objects/Clothing/Uniforms/PMC/standard.rsi
      state: icon
    - type: RandomHumanoidSpawner
      settings: RMCPMCStandard

- type: randomHumanoidSettings
  parent: EventHumanoid
  id: RMCPMCStandard
  components:
    - type: GhostRole
      name: rmc-ghost-role-information-pmc-standard-name
      description: rmc-ghost-role-information-pmc-standard-description
      rules: ghost-role-information-nonantagonist-rules
      raffle:
        settings: short
    - type: Loadout
      prototypes: [ RMCGearPMCStandard ]

- type: startingGear
  id: RMCGearPMCStandard
  equipment:
    # head: /obj/item/clothing/head/helmet/marine/veteran/pmc
    eyes: CMGlassesSecurity
    back: CMBackpack # /obj/item/storage/backpack/lightpack
    gloves: RMCHandsVeteranPMC
    jumpsuit: RMCJumpsuitVeteranPMC
    # outerClothing: /obj/item/clothing/suit/storage/marine/veteran/pmc/light
    shoes: CMBootsBlackFilled
    id: RMCIDCardPMC
    ears: RMCHeadsetDistressPMC
    pocket1: CMPouchFirstAidSplintsGauzeOintment
    pocket2: CMWeaponPistolM77
