- type: job
  parent: CMJobBase
  id: CMCommandingOfficer
  name: cm-job-name-commanding-officer
  description: cm-job-description-commanding-officer
  playTimeTracker: CMJobCommandingOfficer
  requirements:
  - !type:DepartmentTimeRequirement
    department: CMSquad
    time: 54000 # 15 hours
  - !type:TotalJobsTimeRequirement
    group: CMJobsEngineering
    time: 36000 # 10 hours
  - !type:DepartmentTimeRequirement
    department: CMMilitaryPolice
    time: 36000 # 10 hours
  - !type:TotalJobsTimeRequirement
    group: CMJobsMedical
    time: 36000 # 10 hours
  - !type:DepartmentTimeRequirement
    department: CMCommand
    time: 36000 # 10 hours
  - !type:RoleTimeRequirement
    role: CMJobExecutiveOfficer
    time: 36000 #10 hrs
  weight: 10
  startingGear: CMGearCommandingOfficer
  icon: "CMJobIconCommandingOfficer"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: cm-job-supervisors-marine-high-command
  whitelisted: true
  accessGroups:
  - ShipMasterAccess
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      cqc: 2
      construction: 2
      firearms: 1
      fireman: 2
      endurance: 2
      engineer: 2
      execution: 1
      intel: 2
      jtac: 4
      leadership: 3
      medical: 3
      navigations: 1
      overwatch: 1
      police: 2
      powerLoader: 2
      smartGun: 1
      surgery: 1
      vehicles: 1
    - type: MarineOrders

- type: startingGear
  id: CMGearCommandingOfficer
  equipment:
    jumpsuit: CMJumpsuitCO
    back: CMSatchel
    shoes: CMShoesLaceupCommander
    head: CMHeadBeretCO
    outerClothing: CMCoatOfficer
    id: CMIDCardCommandingOfficer
    ears: CMHeadsetSeniorCommand

- type: entity
  parent: CMSpawnPointJobBase
  id: CMSpawnPointCommandingOfficer
  name: commanding officer spawn point
  components:
  - type: SpawnPoint
    job_id: CMCommandingOfficer
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: commanding_officer

- type: playTimeTracker
  id: CMJobCommandingOfficer
