- type: startingGear
  id: RMCGearSurvivorDoctor
  equipment:
    head: CMHeadCapSurgBlue
    mask: CMMaskSterile
    jumpsuit: CMJumpsuitColonist # TODO RMC14 /obj/item/clothing/under/rank/medical
    back: CMSatchelMedical
    gloves: CMHandsLatex
    shoes: ClothingShoesColorWhite
    id: CMIDCardColonist
    ears: CMHeadsetColony
    pocket1: RMCM5Bayonet
    pocket2: RMCFlashlight

- type: entity
  parent: CMSpawnPointJobBase
  id: RMCSpawnPointSurvivorDoctor
  name: survivor doctor spawn point
  components:
  - type: SpawnPoint
    job_id: CMSurvivor
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: survivor
