- type: job
  parent: CMJobBase
  id: CMSurvivor
  name: cm-job-name-survivor
  description: cm-job-description-survivor
  playTimeTracker: CMJobSurvivor
  requirements:
  - !type:DepartmentTimeRequirement
    department: CMSquad
    time: 18000 # 5 hours
  - !type:TotalJobsTimeRequirement
    group: CMJobsEngineering
    time: 18000 # 5 hours
  - !type:TotalJobsTimeRequirement
    group: CMJobsMedical
    time: 18000 # 5 hours
  startingGear: RMCGearSurvivor
  icon: "CMJobIconEmpty"
  joinNotifyCrew: false
  supervisors: cm-job-supervisors-nobody
  accessGroups:
  - Colonist
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      construction: 1
      endurance: 2
      firearms: 1
  hasIcon: false
  hidden: true # TODO RMC14

- type: startingGear
  id: RMCGearSurvivor
  equipment:
    jumpsuit: CMJumpsuitColonist
    back: CMSatchel
    shoes: CMBootsBlack
    id: CMIDCardColonist
    ears: CMHeadsetColony
    pocket1: RMCM5Bayonet
    pocket2: RMCFlashlight

- type: entity
  parent: CMSpawnPointJobBase
  id: CMSpawnPointSurvivor
  name: survivor spawn point
  components:
  - type: SpawnPoint
    job_id: CMSurvivor
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: survivor

- type: playTimeTracker
  id: CMJobSurvivor
