[admin]
deadmin_on_join = true
see_own_notes = true
server_ban_erase_player = true
new_player_threshold = 600

[adminlogs]
server_name = "rouny"

[atmos]
space_wind = false
monstermos_rip_tiles = false
grid_impulse = false

[auth]
mode = 1

[game]
maxplayers = 500
soft_max_players = 250
panic_bunker.enabled = false
round_end_pvs_overrides = false

[ghost]
kill_crit = false
role_time = 0

[hub]
# Set to true to show this server on the public server list
# Before enabling this, read: https://docs.spacestation14.io/hosts/hub-rules
advertise = true

# Comma-separated list of tags, useful for categorizing your server.
# See https://docs.spacestation14.io/hosts/hub-rules for more details on this when it becomes relevant.
tags = "lang:en,region:am_n_e,rp:med"

[ic]
flavor_text = true
enable_suicide = false

[infolinks]
#appeal = "https://appeal.rouny-ss14.com"
bug_report = "https://github.com/RMC-14/RMC-14/issues/new?assignees=&labels=&projects=&template=issue_report.md&title="
discord = "https://discord.gg/rouny"
#forum = "https://forum.rouny-ss14.com"
github = "https://github.com/RMC-14/RMC-14"
patreon = "https://www.patreon.com/RMC14"
#website = ""
#wiki = ""

[log]
path = "logs"
format = "log_%(date)s-%(time)s.txt"
level = 1
enabled = false

[net]
tickrate = 25
port = 1212
bindto = "::,0.0.0.0"
max_connections = 1024

[physics]
maxlinvelocity = 51
grid_splitting = false
target_minimum_tickrate = 120

[replay]
auto_record = true
max_compressed_size = 2097152
max_uncompressed_size = 4194304

[rmc]
discord_account_linking_message_link = "https://discord.com/channels/1168210010233376858/1256765329002991679/1256767294839980132"

[shuttle]
auto_call_time = 0

[status]
# The status server is the TCP side, used by the launcher to determine engine version, etc.
# To be clear: Disabling it makes the launcher unable to connect!
enabled = true

# This is the address and port the status server binds to.
# The port is by default set based on net.port so it will follow what you set there.
bind = "*:1212"
