- type: job
  parent: CMJobBase
  id: CMAuxiliarySupportOfficer
  name: cm-job-name-aso
  description: cm-job-description-aso
  playTimeTracker: CMJobAuxiliarySupportOfficer
  requirements:
  - !type:DepartmentTimeRequirement
    department: CMSquad
    time: 18000 # 5 hours
  - !type:DepartmentTimeRequirement
    department: CMRequisitions
    time: 18000 # 5 hours
  - !type:TotalJobsTimeRequirement
    group: CMJobsEngineering
    time: 18000 # 5 hours
  - !type:DepartmentTimeRequirement
    department: CMAuxiliarySupport
    time: 18000 # 5 hours
  weight: 5
  startingGear: CMGearASO
  icon: "CMJobIconASO"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: cm-job-supervisors-co
  accessGroups:
  - ASO
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      construction: 2
      engineer: 2
      firearms: 1
      fireman: 1
      intel: 2
      jtac: 3
      leadership: 3
      medical: 2
      navigations: 1
      overwatch: 1
      pilot: 2
      police: 1
      powerLoader: 2
      surgery: 1
      vehicles: 1
    - type: MarineOrders

- type: startingGear
  id: CMGearASO
  equipment:
    jumpsuit: CMJumpsuitBO
    outerClothing: CMCoatASO
    back: CMSatchel
    shoes: CMBootsBlack
    id: CMIDCardASO
    ears: RMCHeadsetMarineCommandAlternative
    pocket1: CMPouchGeneralLarge
    pocket2: CMPouchGeneralLarge

- type: entity
  parent: CMSpawnPointJobBase
  id: CMSpawnPointASO
  name: auxiliary support officer spawn point
  components:
  - type: SpawnPoint
    job_id: CMAuxiliarySupportOfficer
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: auxiliary_support_officer

- type: playTimeTracker
  id: CMJobAuxiliarySupportOfficer
