- type: entity
  save: false
  parent: BaseMobSpecies
  id: CMBaseMobSpeciesOrganic
  abstract: true
  name: Urist C.M. McHands
  suffix: RMC14
  components:
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeCircle
          radius: 0.35
        density: 185
        restitution: 0.0
        mask:
        - MobMask
        layer:
        - MobLayer
  - type: SolutionContainerManager
  - type: InjectableSolution
    solution: chemicals
  - type: Bloodstream
    bloodReagent: Blood
    bloodMaxVolume: 560
    maxBleedAmount: 50
    bleedReductionAmount: 0
    bloodRefreshAmount: 0.15
    bloodlossDamage:
      types:
        Bloodloss: 0.5
    bloodlossHealDamage:
      types:
        Bloodloss: -1
    damageBleedModifiers: CMBloodlossHuman
  - type: Woundable
  - type: StatusEffects
    allowed:
    - Stun
    - KnockedDown
    - SlowedDown
    - Stutter
    - SeeingRainbows
    - Electrocution
    - ForcedSleep
    - TemporaryBlindness
    - Drunk
    - SlurredSpeech
    - RatvarianLanguage
    - PressureImmunity
    - Muted
    - Pacified
    - StaminaModifier
    - Flashed
  - type: Blindable
  - type: Tag
    tags:
    - CanPilot
    - FootstepSound
    - DoorBumpOpener
  - type: Marine
  - type: HolocardState
  - type: Hunger
  - type: Thirst
    baseDecayRate: 0.01666666666
  - type: Body
    prototype: Human
    requiredLegs: 2
  - type: Damageable
    damageContainer: Biological
    damageModifierSet: null
    healthBarThreshold: 5
  - type: Vocal
    sounds:
      Male: MaleHuman
      Female: FemaleHuman
      Unsexed: MaleHuman
  - type: Flammable
    fireSpread: false
    canResistFire: true
    damage:
      types:
        Heat: 3
  - type: FireVisuals
    sprite: Mobs/Effects/onfire.rsi
    normalState: Generic_mob_burning
    alternateState: Standing
  - type: MeleeWeapon
    soundHit:
      collection: Punch
    angle: 30
    animation: WeaponArcFist
    attackRate: 1
    damage:
      types:
        Blunt: 5
  - type: CMSurgeryTarget
  - type: UserInterface
    interfaces:
      enum.VoiceMaskUIKey.Key:
        type: VoiceMaskBoundUserInterface
      enum.HumanoidMarkingModifierKey.Key:
        type: HumanoidMarkingModifierBoundUserInterface
      enum.StrippingUiKey.Key:
        type: StrippableBoundUserInterface
      enum.CMSurgeryUIKey.Key:
        type: CMSurgeryBui
      enum.HolocardChangeUIKey.Key:
        type: HolocardChangeBoundUserInterface
        interactionRange: 0
      enum.CMMobStateActionsUI.Key:
        type: CMGhostActionBui
        requireInputValidation: false
  - type: Infectable
  - type: Tackleable
  - type: Tackle
    stun: 10
  - type: XenoNestable
  - type: Devourable
  - type: ImmuneToClothingRequiredStepTrigger
  - type: Undisposable
  - type: ShortExamine
  - type: MaxDamage
    max: 719 # TODO RMC14 this should be per part and smaller
  - type: Perishable
    rotAfter: 300
  - type: AtmosExposed
  - type: Temperature
    heatDamageThreshold: 325
    coldDamageThreshold: 260
    currentTemperature: 310.15
    specificHeat: 42
  - type: ThermalRegulator
    metabolismHeat: 800
    radiatedHeat: 100
    implicitHeatRegulation: 500
    sweatHeatRegulation: 2000
    shiveringHeatRegulation: 2000
    normalBodyTemperature: 310.15
    thermalRegulationTemperatureThreshold: 25
  - type: DamageMobState
    critDamage:
      types:
        Asphyxiation: 1
    nonDeadDamage:
      types:
        Asphyxiation: -0.33
  - type: NoSlip
  - type: AffectableByWeeds
  - type: UserIFF
  - type: UserLimitHits
  - type: MovementIgnoreGravity
  - type: SlowOnPull
    multiplier: 0.6
  - type: MobThresholds
    thresholds:
      0: Alive
      125: Critical
      200: Dead
  - type: MobStateActions
    actions:
      Critical:
      - CMActionGhost
      Dead:
      - CMActionGhost
  - type: Destructible
    thresholds: []
  - type: NpcFactionMember
    factions:
    - UNMC
